---
filename: /var/log/caddy/access.log
labels:
  type: caddy
---
filenames:
  - /var/log/auth.log
labels:
  type: syslog
---
appsec_config: crowdsecurity/appsec-default
labels:
  type: appsec
listen_addr: 0.0.0.0:7422
source: appsec
